version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        container_name: elasticsearch
        networks:
            - elk
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
        volumes:
            - esdata:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.0
        container_name: kibana
        networks:
            - elk
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
    logstash:
        image: docker.elastic.co/logstash/logstash:7.12.0
        container_name: logstash
        networks:
            - elk
        volumes:
            - ./logstash:/usr/share/logstash/pipeline/
        ports:
            - 5044:5044
        depends_on:
            - elasticsearch
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.12.0
        container_name: filebeat
        networks:
            - elk
        volumes:
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
        depends_on:
            - logstash
networks:
    elk:
        driver: bridge
volumes:
    esdata:
        driver: local
