version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=babble
      - POSTGRES_USER=babble
      - POSTGRES_PASSWORD=babble
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
      
volumes:
  postgres_data:
