# Generated by Django 4.1.5 on 2023-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babble", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("audio", models.FileField(upload_to="audio/%Y/%m/%d")),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
