# Generated by Django 4.1.5 on 2023-03-02 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
